Book/urls.py
from django.urls import path

from django.contrib import admin

from Book.views import log, register, BookHome
from Book import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', log.as_view()),
    path('register/', register.as_view()),
    path('bookhome/', BookHome.as_view()),
    # 支付宝
    path('book/',views.shopping),
    path('purchase/<goods_id>/',views.purchase),
    path('show_msg/',views.show_msg),
    # path('check_order/',views.check_order)

]

Book/models.py
from django.db import models


class BookCategory(models.Model):

    name = models.CharField("类别名称",max_length=32)

    class Meta:
        db_table = "BookCategory"

class BookName(models.Model):

    name = models.CharField("书籍名字",max_length=32)
    author  = models.CharField("作者",max_length=32)
    images = models.CharField("书籍封面",max_length=32)
    category = models.ForeignKey(BookCategory,on_delete=BookCategory)

    class Meta:
        db_table = "BookName"

class BookContent(models.Model):
    sheet = models.CharField("章节名称",max_length=32)
    content = models.TextField("章节内容")

    class Meta:
        db_table = "BookContent"


class User(models.Model):
    username = models.CharField("用户名",max_length=32)
    password = models.CharField("用户密码",max_length=61)

    class Meta:
        db_table = "User"

# 支付宝支付用
class BookShoppingOrdering(models.Model):
    order_number = models.CharField(max_length=64)
    status_choices = ((0, '未支付'), (1, '已支付'))
    order_status = models.IntegerField(choices=status_choices, default=0)
    goods = models.ForeignKey(to='BookName', on_delete=models.CASCADE)

templates/book_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>
<h1>哈哈</h1>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="stylesheet" href="../static/css/reset.css">
    <link rel="stylesheet" href="../static/css/supersized.css">
    <link rel="stylesheet" href="../static/css/style.css">

</head>
<body>
<div class="page-container">
    <h1>Login</h1>
    <form action="" method="post">{% csrf_token %}
        <input type="text" name="username" class="username" placeholder="Username">
        <input type="password" name="password" class="password" placeholder="Password">
        <p>{{ err_msg }}</p>
        <button type="submit">登陆</button>
        <a href="/register/">註冊</a>
        <div class="error"><span>+</span></div>
    </form>
</div>

<script src="../static/js/jquery-1.8.2.min.js"></script>
<script src="../static/js/supersized.3.2.7.min.js"></script>
<script src="../static/js/supersized-init.js"></script>
<script src="../static/js/scripts.js"></script>

<ul id="supersized" class="quality" style="visibility: visible;">
    <li class="slide-0" style="visibility: visible; opacity: 1;">
        <a target="_blank">
            <img
                src="../static/img/backgrounds/1.jpg" style="width: 1583px; left: 0px; top: -393px; height: 1108.1px;">
        </a>
    </li>
    <li class="slide-1 prevslide" style="visibility: visible; opacity: 1;">
        <a target="_blank">
            <img
            src="../static/img/backgrounds/2.jpg" style="width: 1583px; left: 0px; top: -393px; height: 1108.1px;">
        </a>
    </li>
    <li class="slide-2 activeslide" style="visibility: visible; opacity: 1;">
        <a target="_blank">
            <img
            src="../static/img/backgrounds/3.jpg"
            style="width: 1583px; height: 1060.61px; left: 0px; top: -369.5px;">
        </a></li>
</ul>
</body>
</html>

templates/order_list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>订单信息</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <div class="row" style="margin-top: 10px">
        <h4 style="text-align: center;font-weight: bold">Django支付宝支付案例</h4>
    </div>
    <div class="row" style="margin-top: 10px">
        <div class="col-md-8 col-md-offset-2">
            <table class="table table-bordered">
                <tr style="text-align: center">
                    <th style="text-align: center">订单ID</th>
                    <th style="text-align: center">订单号</th>
                    <th style="text-align: center">订单状态</th>
                    <th style="text-align: center">商品名称</th>
                    <th style="text-align: center">商品价格</th>
                </tr>
                {% for row in order_obj %}
                    <tr style="text-align: center">
                        <td>{{ row.id }}</td>
                        <td>{{ row.order_number }}</td>
                        <td>{{ row.get_order_status_display }}</td>
                        <td>{{ row.goods.goods_name }}</td>
                        <td>{{ row.goods.goods_price }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
<div class="container-fluid" style="color: #b2bcc5;margin-top: 20px;margin-bottom: 2px">
    <div class="row">
        <div class="col-md-12  text-center" style="padding: 40px">
            Copyright © 2019-2020&nbsp;蓝色旗帜 版权所有&nbsp;
            <a target="_blank_" href="http://www.miit.gov.cn/" style="color:#b2bcc5;">豫ICP备19014367号-1</a>
        </div>
    </div>
</div>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
</head>
<body>
 <div class="form-group">
    <label for="inputUsername3" class="col-sm-2 control-label">Username</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="inputUsername" placeholder="Username" name="username">
    </div>
  </div>
  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
      <input type="password" class="form-control" id="inputPassword" placeholder="Password" name="password">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button id="ajaxTest" class="btn btn-default">注册</button>
    </div>
  </div>
 <script>
      $("#ajaxTest").click(function () {
    $.ajax({
      url: "/register/",
      type: "POST",
      data: {username: $("#inputUsername").val(), password:$("#inputPassword").val() },
      success: function (data) {
        alert(data)
      }
    })
  })
 </script>



{#<form class="form-horizontal" action="" method="post">{% csrf_token %}#}
{#  <div class="form-group">#}
{#    <label for="inputUsername3" class="col-sm-2 control-label">Username</label>#}
{#    <div class="col-sm-10">#}
{#      <input type="text" class="form-control" id="" placeholder="Username" name="username">#}
{#    </div>#}
{#  </div>#}
{#  <div class="form-group">#}
{#    <label for="inputPassword3" class="col-sm-2 control-label">Password</label>#}
{#    <div class="col-sm-10">#}
{#      <input type="password" class="form-control" id="inputPassword3" placeholder="Password" name="password">#}
{#    </div>#}
{#  </div>#}
{#  <div class="form-group">#}
{#    <div class="col-sm-offset-2 col-sm-10">#}
{#      <button type="submit" class="btn btn-default">注册</button>#}
{#    </div>#}
{#  </div>#}
{#</form>#}
</body>
</html>

templates/show_msg.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>支付结果</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <div class="row" style="margin-top: 30px">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-primary">
                <div class="panel-body text-center">{{ msg }}！</div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/zhifubaoshopping.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>商品信息</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <div class="row" style="margin-top: 10px">
        <h4 style="text-align: center;font-weight: bold">Django支付宝支付案例</h4>
    </div>
    <div class="row" style="margin-top: 10px">
        <div class="col-md-4 col-md-offset-4">
            <table class="table table-bordered">
                {% for row in goods_list %}
                    <tr style="text-align: center">
                        <td>{{ row.id }}</td>
                        <td>{{ row.name }}</td>
                        <td>{{ 111 }}</td>
                        <td><a href="/purchase/{{ row.id }}">购买</a></td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
<div class="container-fluid" style="color: #b2bcc5;margin-top: 20px;margin-bottom: 2px">
    <div class="row">
        <div class="col-md-12  text-center" style="padding: 40px">
            Copyright © 2019-2020&nbsp;蓝色旗帜 版权所有&nbsp;
            <a target="_blank_" href="http://www.miit.gov.cn/" style="color:#b2bcc5;">豫ICP备19014367号-1</a>
        </div>
    </div>
</div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
</html>